spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:9092/hotelsbase
spring.datasource.username=${DB_USERNAME:test}
spring.datasource.password=${DB_PASSWORD:test}