spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://mysql:9092/hotelsbase
spring.datasource.username=test
spring.datasource.password=test